package main

import (
	"fmt"
	"github.com/gin-contrib/pprof"
	"hzer/configs"
	_ "hzer/docs" // docs is generated by Swag CLI, you have to import it.
	"hzer/internal/mysql"
	"hzer/internal/redis"
	"hzer/internal/router"

	"github.com/gin-gonic/gin"
)

/**
 *                             _ooOoo_
 *                            o8888888o
 *                            88" . "88
 *                            (| -_- |)
 *                            O\  =  /O
 *                         ____/`---'\____
 *                       .'  \\|     |//  `.
 *                      /  \\|||  :  |||//  \
 *                     /  _||||| -:- |||||-  \
 *                     |   | \\\  -  /// |   |
 *                     | \_|  ''\---/''  |   |
 *                     \  .-\__  `-`  ___/-. /
 *                   ___`. .'  /--.--\  `. . __
 *                ."" '<  `.___\_<|>_/___.'  >'"".
 *               | | :  `- \`.;`\ _ /`;.`/ - ` : | |
 *               \  \ `-.   \_ __\ /__ _/   .-` /  /
 *          ======`-.____`-.___\_____/___.-`____.-'======
 *                             `=---='
 *          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *                     佛祖保佑        永无BUG
 *            佛曰:
 *                   写字楼里写字间，写字间里程序员；
 *                   程序人员写程序，又拿程序换酒钱。
 *                   酒醒只在网上坐，酒醉还来网下眠；
 *                   酒醉酒醒日复日，网上网下年复年。
 *                   但愿老死电脑间，不愿鞠躬老板前；
 *                   奔驰宝马贵者趣，公交自行程序员。
 *                   别人笑我忒疯癫，我笑自己命太贱；
 *                   不见满街漂亮妹，哪个归得程序员？
 */

// @title Hzer后端服务
// @version 1.0
// @description Hzer后端API接口文档

// @contact.name API Support
// @contact.url http://www.swagger.io/support

// @license.name MIT
// @license.url https://gitee.com/LoveA/Hzer/blob/master/LICENSE

// @host 127.0.0.1:18080
// @BasePath

func main() {
	configs.InitConfigs()
	InitFunc()

	r := gin.Default()
	///开启性能测试 github.com/gin-contrib/pprof
	pprof.Register(r, fmt.Sprintf("%s/pprof", configs.Env))
	/*
		开启图形测试:https://graphviz.org/download/
		可使用go-wrk基准测试 github.com/adjust/go-wrk
	*/

	//初始化router
	router.NewHTTPRouter(r)

	//开启服务器
	ipAddr := fmt.Sprintf("%s:%d", configs.Data.App.Host, configs.Data.App.Port)
	_ = r.Run(ipAddr)

}

func InitFunc() {
	fmt.Printf("" +
		"\t██╗  ██╗███████╗███████╗██████╗ \n" +
		"\t██║  ██║╚══███╔╝██╔════╝██╔══██╗\n" +
		"\t███████║  ███╔╝ █████╗  ██████╔╝\n" +
		"\t██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗\n" +
		"\t██║  ██║███████╗███████╗██║  ██║\n" +
		"\t╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝\n")

	//初始化数据库
	if configs.Data.Database.Redis.Enable {
		redis.InitRedis(configs.Data.Database.Redis)
	}
	if configs.Data.Database.Mysql.Enable {
		mysql.InitGorm(configs.Data.Database)
	}

}
